#!/bin/bash
# =============================================================================
# 🚀 DEPLOY PARA PRODUÇÃO - Alternativas ao Fly.io
# =============================================================================
# Scripts para deploy em diferentes provedores de nuvem
# =============================================================================

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║           🚀 ESCOLHA SEU PROVEDOR DE PRODUÇÃO              ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "🔥 ALTERNATIVAS RECOMENDADAS:"
echo ""
echo "1. 🟢 VERCEL (Frontend + API) - Mais fácil"
echo "2. 🟠 RAILWAY (Full-stack) - Equilibrado"
echo "3. 🔵 RENDER (Full-stack) - Bom custo-benefício"
echo "4. 🟣 AWS/GCP - Enterprise"
echo ""
echo "💰 CUSTOS APROXIMADOS (por mês):"
echo "   Vercel: $0-20 (hobby)"
echo "   Railway: $5-15 (hobby)"
echo "   Render: $7-25 (starter)"
echo "   AWS: $10-50+ (EC2 + RDS)"
echo ""

read -p "Qual provedor você prefere? (1-4): " choice

case $choice in
    1)
        echo ""
        echo "🟢 VERCEL ESCOLHIDO"
        echo "==================="
        echo ""
        echo "📋 PASSOS PARA VERCEL:"
        echo ""
        echo "1. Instalar Vercel CLI:"
        echo "   npm i -g vercel"
        echo ""
        echo "2. Login:"
        echo "   vercel login"
        echo ""
        echo "3. Deploy do frontend:"
        echo "   vercel --prod"
        echo ""
        echo "4. Deploy da API (Node.js):"
        echo "   vercel --prod --yes"
        echo ""
        echo "5. Configurar variáveis de ambiente no dashboard"
        echo ""
        ;;
    2)
        echo ""
        echo "🟠 RAILWAY ESCOLHIDO"
        echo "===================="
        echo ""
        echo "📋 PASSOS PARA RAILWAY:"
        echo ""
        echo "1. Instalar Railway CLI:"
        echo "   curl -fsSL https://railway.app/install.sh | sh"
        echo ""
        echo "2. Login:"
        echo "   railway login"
        echo ""
        echo "3. Criar projeto:"
        echo "   railway init"
        echo ""
        echo "4. Adicionar serviços:"
        echo "   railway add --name api"
        echo "   railway add --name omr-service"
        echo "   railway add --name tri-service"
        echo ""
        echo "5. Deploy:"
        echo "   railway up"
        echo ""
        ;;
    3)
        echo ""
        echo "🔵 RENDER ESCOLHIDO"
        echo "==================="
        echo ""
        echo "📋 PASSOS PARA RENDER:"
        echo ""
        echo "1. Conectar GitHub no Render.com"
        echo ""
        echo "2. Criar serviços:"
        echo "   • Web Service (Node.js API)"
        echo "   • Web Service (OMR Python)"
        echo "   • Web Service (TRI Python)"
        echo ""
        echo "3. Configurar build commands:"
        echo "   API: npm install && npm run build"
        echo "   Python: pip install -r requirements.txt"
        echo ""
        echo "4. Configurar start commands:"
        echo "   API: npm start"
        echo "   Python: python app.py"
        echo ""
        ;;
    4)
        echo ""
        echo "🟣 AWS/GCP ESCOLHIDO"
        echo "===================="
        echo ""
        echo "📋 PASSOS PARA AWS:"
        echo ""
        echo "1. ECS Fargate (recomendado):"
        echo "   • API: ECS Service + ALB"
        echo "   • DB: RDS PostgreSQL"
        echo "   • Cache: ElastiCache Redis"
        echo ""
        echo "2. Ou EC2 + Docker:"
        echo "   • Instâncias EC2"
        echo "   • Load Balancer"
        echo "   • RDS Database"
        echo ""
        echo "💰 Mais caro, mas escalável"
        echo ""
        ;;
    *)
        echo "❌ Opção inválida"
        exit 1
        ;;
esac

echo ""
echo "🔧 CONFIGURAÇÕES COMUNS PARA TODOS:"
echo ""
echo "1. Variáveis de ambiente:"
echo "   SUPABASE_URL=..."
echo "   SUPABASE_SERVICE_KEY=..."
echo "   OPENAI_API_KEY=..."
echo ""
echo "2. URLs dos serviços:"
echo "   PYTHON_OMR_URL=https://your-omr-service.com"
echo "   PYTHON_TRI_URL=https://your-tri-service.com"
echo ""
echo "3. Banco de dados:"
echo "   • Manter Supabase (já está em produção)"
echo "   • Ou migrar para PostgreSQL do provedor"
echo ""

echo "📞 SUPORTE:"
echo "   Vercel: vercel.com/docs"
echo "   Railway: railway.app/docs"
echo "   Render: render.com/docs"
echo "   AWS: aws.amazon.com/getting-started"